baseURL      = "https://bore.vip/"
languageCode = "zh-CN"
theme = "hugo-theme-stack"
title = "Bore's Notes"

# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "zh"

# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage = true

# Enable Git info for commit information
enableGitInfo = true

# gitRepo = "https://github.com/iwyang/hugo"

# [[module.imports]]
    # path = "github.com/CaiJimmy/hugo-theme-stack/v3"
	
[outputs]
    home = ["HTML", "RSS", "JSON"]	

[pagination]
    pagerSize = 10

[permalinks]
    post = "/archives/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
	
[frontmatter]
# 修复了引号和拼写错误 (default)
lastmod = [":git", "lastmod", ":fileModTime", ":default"]

