mainSections = ["post","shuoshuo"]
rssFullContent = true
favicon        = "img/avatar.png"

# ğŸ‘‡ ===== æ–°å¢çš„æ—¥æœŸæ ¼å¼é…ç½® ===== ğŸ‘‡
[dateFormat]
    published = "2006-01-02" # è¿™æ ·ä¼šæ˜¾ç¤ºä¸º 2024-04-06 (å¸¦å‰å¯¼é›¶æ›´å¥½çœ‹)
    # å¦‚æœä½ åšæŒä¸¥æ ¼è¦ "2024-4-6"ï¼ˆä¸å¸¦å‰å¯¼é›¶ï¼‰ï¼Œè¯·æŠŠä¸Šä¸€è¡Œæ”¹æˆ published = "2006-1-2"
    lastUpdated = "2006-01-02 15:04"
# ğŸ‘† ================================ ğŸ‘†

[footer]
    since = 2020

[sidebar]
    emoji    = "ğŸ¥"
    subtitle = "åšè§‚è€Œçº¦å–ï¼Œåšç§¯è€Œè–„å‘"
    avatar   = "img/avatar.png"

[article]
    readingTime = true  # ç¡®ä¿å¼€å¯é˜…è¯»æ—¶é—´/ç›¸å…³å…ƒæ•°æ®åŠŸèƒ½
    [article.license]
        enabled = false
        default = "Licensed under CC BY-NC-SA 4.0"
	[article.edit]
        enabled = true	

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    # See complete configuration in config/_default/params.toml
    enabled  = true
    provider = "twikoo"
    [comments.twikoo]
	    # envId: https://twikoo-lake.vercel.app
        envId = "https://t.bore.vip"
        # region =
        # path =
        # lang =