mainSections = ["post"]
rssFullContent = true
favicon        = "img/avatar.png"

# --- æ–°å¢è¿™è¡Œä»£ç  ---
customCSS      = ["custom.scss"]
# ------------------

[footer]
    since = 2020

[sidebar]
    emoji    = "ğŸ¥"
    subtitle = "åšè§‚è€Œçº¦å–ï¼Œåšç§¯è€Œè–„å‘"
    avatar   = "img/avatar.png"

[article]
    [article.license]
        enabled = false
        default = "Licensed under CC BY-NC-SA 4.0"
	[article.edit]
        enabled = true	

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    # See complete configuration in config/_default/params.toml
    enabled  = true
    provider = "twikoo"
    [comments.twikoo]
	    # envId: https://twikoo-lake.vercel.app
        envId = "https://t.bore.vip"
        # region =
        # path =
        # lang =

